#!/usr/bin/env python

import os
import sys
import json
import logging

logging.basicConfig(stream=sys.stderr, level=logging.DEBUG)
log = logging.getLogger(__name__)

sys.stdout.write("// File generated by %s, do not edit\n" % sys.argv[0])
sys.stdout.write("/* eslint no-trailing-spaces: 0, comma-dangle: 0, max-len: 0, quotes: 0 */\n")
sys.stdout.write("import Textures from \"SC/Textures\";\n\n")

for filename in os.listdir(os.path.join("textures")):
  path = os.path.join("textures", filename)
  if filename in [".DS_Store", "README.md"] or not os.path.isfile(path):
    continue
  sys.stdout.write("Textures.createTexture('%s', '%s');\n" % (filename, path))
